[package]
name = "mrrobot"
version = "0.1.0"
authors = ["Kike Font√°n (@CosasDePuma) <kikefontanlorenzo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
yaml-rust = "0.4.3"